canonical: https://www.medizininformatik-initiative.de/fhir/core/modul-person
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: mii-ig-person
name: MII_IG_Person
status: active
version: 2025.0.0
packageId: de.medizininformatikinitiative.kerndatensatz.person
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  de.basisprofil.r4: 1.5.0
  de.medizininformatikinitiative.kerndatensatz.meta: 2025.0.0-alpha3

menu:
  Home: index.html
  Artifacts: artifacts.html